sudo: false
language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - ~/.yarn
    - node_modules
env:
  global:
    - YARN_VERSION=1.3.2

before_install:
  - |
    if [[ ! -e ~/.yarn/bin/yarn || $(yarn --version) != "${YARN_VERSION}" ]]; then
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
    fi

after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
